version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./resources/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - 8080:8080
    depends_on:
    - postgres
    links: 
      - cron-service:cron-service
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  cron-service:
    build: 
      context: ./cron-service
    ports:
    - 3000:3000
    environment:
      POSTGRES_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    restart: always
#  web-ui:
#    build: 
#      context: ./game-statistics-ui
#    ports: 
#    - 8088:3000
#    restart: on-failure
#    command: node server.js
volumes:
  db_data: